# ---------- Defaults & tuning ----------
TARGET_SR = 16000
BLOCKSIZE = 1024
CHANNELS = 1

# VAD / energy defaults
VAD_FRAME_MS = 30
MIN_VOICED_SECONDS = 0.15
VAD_AGGRESSIVENESS = 2
SPEECH_RATIO_THRESHOLD = 0.03
NOISE_HISTORY_SECONDS = 10.0
NOISE_UPDATE_SKIP_VOICED = True
NOISE_MULTIPLIER = 1.8
MIN_SEGMENT_DURATION = 0.1
DUPLICATE_SIMILARITY = 0.85

# Poetry-specific settings 
WORD_SIMILARITY_THRESHOLD = 0.7
TITLE_SIMILARITY_THRESHOLD = 0.6

# Multi-word processing settings
MAX_WORDS_PER_CHUNK = 5
PARTIAL_MATCH_BONUS = 0.1
